### PR TITLE
More precise basemap, lighter colours

### PR DESCRIPTION
**Pull request by peterdesmet**

### CODE REVIEW

**Comment by peterdesmet** [comment]
## Before

before

## After

after

We'll have to assess if those new colours work better on paper, in a presentation, etc.

@hvangasteren, notice IJselmeer! :smile:

**Comment by jshamoun** [comment]
This looks great, borders, water bodies and colors, fantastic. Let's try it out on the beamer today.

**Comment by hvangasteren** [comment]
JJJ

 

Thanks

 

Van: Peter Desmet [mailto:notifications@github.com] 
Verzonden: donderdag 11 juni 2015 2:53
Aan: enram/bird-migration-flow-visualization
CC: Hans van Gasteren
Onderwerp: Re: [bird-migration-flow-visualization] More precise basemap, lighter colours (#115)

 


Before


 <https://cloud.githubusercontent.com/assets/600993/8097605/9bddc658-0fe4-11e5-81da-53ed90a7f890.png> before


After


 <https://cloud.githubusercontent.com/assets/600993/8097607/a309e7a4-0fe4-11e5-8d46-8b5f2b4f4887.png> after

We'll have to assess if those new colours work better on paper, in a presentation, etc.

@hvangasteren <https://github.com/hvangasteren> , notice IJselmeer!  :smile: <https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png>

**Comment by peterdesmet** [comment]
Checked on beamer with @jshamoun. Increased particle size a bit more, now looks great.

**Pull request merged**
